use v6;

#
# This program creates metrics modules for some fonts and place them
# under the "Metrics" directory.
#
# Author: Gisle Aas
# Perl 5 -> 6 Port: David Warring

BEGIN %*ENV<METRICS> //= 'etc/Core14_AFMs';

use Font::AFM;
use Panda::Builder;
use Panda::Common;

BEGIN our @FONTS = <Courier
    Courier-Bold
    Courier-Oblique
    Courier-BoldOblique

    Helvetica
    Helvetica-Bold
    Helvetica-Oblique
    Helvetica-BoldOblique
  
    Times-Roman
    Times-Bold
    Times-Italic
    Times-BoldItalic
    >;

class Build is Panda::Builder {

    method build($where) {

        indir $where, {
            my $class-dir = $*SPEC.catdir('lib', 'Font', 'Metrics');
            mkdir( $class-dir, 0o755);

            for @FONTS -> $font {
                (my $fontmod = $font) ~~ s:g/'-'//;
                my $class-name = "Font::Metrics::$fontmod";
        
                say "Building $font => $class-name";
                {
                    my $afm = Font::AFM.new: $font;

                    my $font-path = $*SPEC.catfile($class-dir, "$fontmod.pm");
                    my $*OUT = open( $font-path, :w);

                    my $metrics = %( $afm ).item;

                    print q:s:c:to"--CODE-GEN--";
                    use v6;
                    # Font metrics for $font
                    #
                    # DO NOT EDIT!!!
                    #
                    # This file was auto-generated by {$*SPEC.abs2rel($?FILE)} based on the AFM file for the font.
                    #
                    # {$afm.Notice}

                    use Font::AFM;

                    class $class-name
                        is Font::AFM;
                    
                    --CODE-GEN--
  
                    say "BEGIN our \$metrics = {$metrics.perl}";
                    say '';
                    say 'method new { self.bless( :$metrics ) }';
                }
            }
        }
    }
}

# Build.pm can also be run standalone 
sub MAIN(:$indir = '.', :$metrics-path?, *@font-names ) {

    %*ENV<METRICS> = $metrics-path
        if $metrics-path.defined;

    @FONTS = @font-names
        if +@font-names;

    Build.new.build($indir);
}
